/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-14 11:42:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"css/index.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<section>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("       <h2 class=\"title\">Kayit Ol</h2>\r\n");
      out.write("        <form class=\"form form2\" action=\"worldServlet\"  method=\"POST\" \r\n");
      out.write("							>\r\n");
      out.write("                    <div class='formInput'>\r\n");
      out.write("                        <div class=\"form-label\">Ad</div>\r\n");
      out.write("                        <div class='input-group'>\r\n");
      out.write("                            <input class=\"form__input\" id=\"firstName\" name=\"firstName\"  />\r\n");
      out.write("                        </div>\r\n");
      out.write("                            <p id=\"firstNameError\" style=\"color: red;position: absolute;margin-bottom: -50px\"></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                      <div class='formInput'>\r\n");
      out.write("                        <div class=\"form-label\">Soyad</div>\r\n");
      out.write("                        <div class='input-group'>\r\n");
      out.write("                            <input class=\"form__input\" id=\"lastName\" name=\"lastName\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                            <p id=\"lastNameError\" style=\"color: red;position: absolute;margin-bottom: -50px\"></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                     <div class='formInput'>\r\n");
      out.write("                        <div class=\"form-label\">Email</div>\r\n");
      out.write("                        <div class='input-group'>\r\n");
      out.write("                            <input class=\"form__input\" id=\"email\" name=\"email\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                            <p id=\"emailError\" style=\"color: red;position: absolute;margin-bottom: -50px\"></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                     <div class='formInput'>\r\n");
      out.write("                        <div class=\"form-label\">Sifre</div>\r\n");
      out.write("                        <div class='input-group'>\r\n");
      out.write("                            <input class=\"form__input\" id=\"password\" name=\"password\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                            <p id=\"passwordError\" style=\"color: red;position: absolute;margin-bottom: -50px\"></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   \r\n");
      out.write("                    <div class='formInput'>\r\n");
      out.write("                        <div class=\"form-label\">Cep Telefonu</div>\r\n");
      out.write("                        <div class='input-group'>\r\n");
      out.write("                            <input class=\"form__input\" id=\"phoneNumber\" name=\"phoneNumber\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                           <p id=\"phoneNumberError\" style=\"color: red;position: absolute;margin-bottom: -50px\"></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                     <div class='formInput'>\r\n");
      out.write("                        <div class=\"form-label\">Cinsiyet</div>\r\n");
      out.write("                        <div class='input-group'>\r\n");
      out.write("                            <select name=\"gender\" class=\"form__input\" id=\"gender\" style=\"padding-right: 5px\">\r\n");
      out.write(" <option value=\"-1\">Seciniz...</option>\r\n");
      out.write("  <option value=\"Erkek\">Erkek</option>\r\n");
      out.write("  <option value=\"Kadin\">Kadin</option>\r\n");
      out.write("</select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                           <p id=\"genderError\" style=\"color: red;position: absolute;margin-bottom: -42px\"></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                     <div class='formInput'>\r\n");
      out.write("                        <div class=\"form-label\">Dogum Tarihi</div>\r\n");
      out.write("                        <div class='input-group'>\r\n");
      out.write("                            <input class=\"form__input\" id=\"dateOfBirth\" name=\"dateOfBirth\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                           <p id=\"dateOfBirthError\" style=\"color: red;position: absolute;margin-bottom: -50px\"></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   \r\n");
      out.write("                    <div class=\"button-submit\">\r\n");
      out.write("                        <input class=\"submitButton\" type=\"submit\" value=\"Gonder\"></input>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("		\r\n");
      out.write("    </div>\r\n");
      out.write("   </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("			let existsForFirstName = false;\r\n");
      out.write("			let existsForLastName = false;\r\n");
      out.write("			let existsForEmail = false;\r\n");
      out.write("			let existsForGender = false;\r\n");
      out.write("			let existsForPassword = false;\r\n");
      out.write("			let existsForPhoneNumber = false;\r\n");
      out.write("			let existsForDateOfBirth = false;\r\n");
      out.write("			\r\n");
      out.write("			function isEmpty(input,elementId,errorMessage){\r\n");
      out.write("				if(input.trim() === \"\"){\r\n");
      out.write("					$(elementId).html(\" * \"+errorMessage +\" bos gecilemez\");\r\n");
      out.write("					return true;\r\n");
      out.write("				}else{\r\n");
      out.write("					$(elementId).html(\"\");\r\n");
      out.write("					return false;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			function validateFirstName(){\r\n");
      out.write("				let firstName = $(\"#firstName\").val();\r\n");
      out.write("				existsForFirstName =  isEmpty(firstName,\"#firstNameError\",\"Isim\");\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			function validateLastName(){\r\n");
      out.write("				let lastName = $(\"#lastName\").val();\r\n");
      out.write("				existsForLastName = isEmpty(lastName,\"#lastNameError\",\"Soyad\");\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			function validateEmail(){\r\n");
      out.write("				let email = $(\"#email\").val();\r\n");
      out.write("				existsForEmail = isEmpty(email,\"#emailError\",\"Email\");\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			function validateGender() {\r\n");
      out.write("				let gender = $(\"#gender\").val();\r\n");
      out.write("				if(gender == -1){\r\n");
      out.write("					$(\"#genderError\").html(\" * Cinsiyet bos gecilemez\");\r\n");
      out.write("					existsForGender = true;\r\n");
      out.write("				}else{\r\n");
      out.write("					$(\"#genderError\").html(\"\");\r\n");
      out.write("					existsForGender = false;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			function validatePassword() {\r\n");
      out.write("				let password = $(\"#password\").val();\r\n");
      out.write("				existsForPassword = isEmpty(password,\"#passwordError\",\"Sifre\");\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			function validateDateOfBirth(){\r\n");
      out.write("				let dateOfBirth = $(\"#dateOfBirth\").val();\r\n");
      out.write("				existsForDateOfBirth = isEmpty(dateOfBirth,\"#dateOfBirthError\",\"Dogum tarih\");\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			function validatePhoneNumber() {\r\n");
      out.write("				let phoneNumber = $(\"#phoneNumber\").val();\r\n");
      out.write("				existsForPhoneNumber = isEmpty(phoneNumber,\"#phoneNumberError\",\"Telefon numarasi\");\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			 $(\".form2\").submit(function (e) {\r\n");
      out.write("				   	e.preventDefault();\r\n");
      out.write("				   	validateFirstName();\r\n");
      out.write("				    validateLastName();\r\n");
      out.write("				    validateEmail();\r\n");
      out.write("				    validateGender();\r\n");
      out.write("				    validatePassword();\r\n");
      out.write("				    validateDateOfBirth();\r\n");
      out.write("				    validatePhoneNumber();\r\n");
      out.write("				    if (\r\n");
      out.write("				    		!existsForFirstName &&\r\n");
      out.write("							!existsForLastName &&\r\n");
      out.write("							!existsForEmail &&\r\n");
      out.write("							!existsForGender &&\r\n");
      out.write("							!existsForPassword && \r\n");
      out.write("							!existsForPhoneNumber &&\r\n");
      out.write("							!existsForDateOfBirth\r\n");
      out.write("				    ) {\r\n");
      out.write("		                   this.submit(); \r\n");
      out.write("		   \r\n");
      out.write("				    } \r\n");
      out.write("				  });\r\n");
      out.write("		})\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
